### ISSUE TITLE
la_vector will crash with this piece of data

### ISSUE THREAD

**Issue by VincentXWD** [gvinciguerra/la_vector#2]
try this sequence:
`15756253474322382864
15756253976833556496
15756525753774112784
15757004406404415504
16279747014894288912
16283133381858820112
16283133476348100624
16283244831965184016
16283938310269698064
16284004804953374736
16442457586000723984
16443349573398691856
16445391963491926032
16445391967786893328
16451901171112607760
16466779307193139216
16466828278410248208
16466940742128893968
16468832907151015952
16469339408349265936
16470028742010339344
16470201378220802064
16470201386810736656
16470495991502471184
16470580636717940752
16470580662487744528
16470582530798518288
16470583690439688208
16470583991087398928
16470585425606475792
16470586645377187856
16470586649672155152
16470609047926603792
16471520650440212496
16471616080318562320
16471768414218616848
16472359144020508688
16472359238509789200
16472428877109526544
16473174157014597648
16473336755886489616
16473380671927091216
16473406411666096144
16473909146178027536
16474157159064535056
16474158516274200592
16474158529159102480
16474563054948843536
16474644173996163088
16475069414413172752
16475213437551509520
16475221988831395856
16475499572567736336
16475499598337540112
16475827312932159504
16475875790228029456
16475878066560696336
16475879136007553040
16475879389410623504
16475945626396262416
16475994116577034256
16476129764529143824
16476131233407959056
16476465583727050768
16476626692245291024
16476663465755279376
16476675530318413840
16476675861030895632
16476701725323952144
16476704929369554960
16476763890680594448
16476857911809671184
16476960316714909712
16477040022717988880
16477583847182041104
16478016071215874064
16478016075510841360
16478158067129647120
16478239216241737744
16478371574248898576
16478417526103998480
16478417573348638736
16478417891176218640
16478949028306878480
16479110798250082320
16479481642906288144
16479481647201255440
16479483992253399056
16479936067626074128
16480231784714338320
16480808006116704272
16481527649361985552
16482094997361917968
16482971308129255440
16483763699530596368
16483763905689026576
16483962702545289232
16483963703272669200
16483963729042472976
16484199698840682512
16484291847364018192
16485413654167027728
16485458274582265872
16485569509940264976
16485893943179870224
16485894037669150736
16485900334091206672
16486168013632962576
16486168039402766352
16486174245630509072
16486174619292663824
16486174782501421072
16486175366616973328
16486189926556106768
16487042958600699920
16487499805682040848
16488245884451029008
16488538779745779728
16489555570303434768
16489557189506105360
16489557215275909136`

**Comment by gvinciguerra** [comment]
Thanks. It should be fixed now
